/**
 * Returns data.
 * Data must be provided this way because is not possible to read a local file without an underlying webserver.
 * 
 * @returns Array
 */
function provider()
{
    return ["~GENNAIO 2024",
    " 1                 Lunedì",
    "                   SS. Maria madre di Dio",
    " 2                 Martedì",
    "                   S. Basilio Vescovo",
    " 3                 Mercoledì",
    "                   S. Genoveffa",
    "                                                                              SECCO",
    " 4                 Giovedì",
    "                   S. Ermete",
    "                                                                              CARTA",
    " 5                 Venerdì",
    "                   S. Amelia",
    "                                                                              UMIDO",
    "                                                                                            tanti giochi per i",
    "                                                                                           bambini;",
    "                                                                                            diversi tipi di tessuti;",
    " 6                 Sabato",
    "                   Epifania del Signore",
    "                                                                                            oggetti utili per la casa.",
    " 7",
    "                                                                                           Fonte: COREPLA",
    "                   Domenica",
    "                   S. Luciano",
    " 8                 Lunedì",
    "                   S. Severino, S. Massimo",
    "                                                                              SECCO",
    " 9                 Martedì",
    "                   S. Giuliano martire",
    "                                                              UMIDO           VERDE",
    " 10                Mercoledì",
    "                   S. Aldo Eremita",
    "                                                                            PLASTICA",
    " 11                Giovedì                                                    VETRO          PRODOTTI DI",
    "                                                                                             STAGIONE",
    "                   S. Igino Papa",
    " 12                Venerdì",
    "                   S. Modesto",
    "                                                                              UMIDO",
    "                                                                                           FRUTTA",
    " 13                Sabato",
    "                   S. Ilario                                                               arance bionde,",
    "                                                                                           clementine, limoni,",
    " 14                Domenica",
    "                   S. Felice",
    "                                                                                           cedri, mandarini,",
    "                                                                                           pompelmi, mele, pere",
    " 15                Lunedì",
    "                   S. Mauro",
    "                                                                              SECCO",
    " 16                Martedì",
    "                   S. Marcello Papa",
    "                                                                              UMIDO",
    " 17                Mercoledì",
    "                   Sant’Antonio Abate",
    "                                                                                           VERDURA",
    " 18                Giovedì                                                                 varietà di cavolo,",
    "                                                                              CARTA",
    "                   S. Liberata, S. Prisca",
    "                                                                                           bietole, broccoli,",
    "                                                                                           carciofi, carote, cipolle,",
    " 19                Venerdì",
    "                   S. Mario Martire",
    "                                                                              UMIDO        finocchi, lattuga,",
    "                                                                                           patate, porri, radicchio,",
    "                                                                                           rosso, rape, sedano,",
    " 20                Sabato",
    "                   S. Sebastiano",
    "                                                                                           spinaci",
    " 21                Domenica",
    "                   S. Agnese",
    " 22                Lunedì",
    "                   S. Vincenzo",
    "                                                                              SECCO",
    " 23                Martedì",
    "                   S. Emerenziana",
    "                                                              UMIDO           VERDE",
    "                                                                                             NUMERI",
    " 24                Mercoledì",
    "                   S. Francesco di Sales",
    "                                                                            PLASTICA         UTILI",
    " 25                Giovedì",
    "                   Conversione di S. Paolo",
    "                                                                              VETRO",
    "                                                                                             SEGNALAZIONI E PRENOTAZIONI",
    "                                                                                             RIFIUTI SU CHIAMATA",
    " 26                Venerdì                                                                   800.969.852",
    "                                                                              UMIDO",
    "                   S. Tito, S. Timoteo",
    " 27                Sabato",
    "                   S. Angela Merici",
    "                                                                                             RIFIUTI SPECIALI",
    "                                                                                             0429 1580211",
    " 28                Domenica",
    "                   S. Tommaso d’ Aquino",
    " 29                Lunedì",
    "                   S. Costanzo",
    "                                                                              SECCO          WHATSAPP",
    "                                                                                             348 6705764",
    " 30                Martedì",
    "                   S. Martina",
    "                                                                              UMIDO",
    " 31                Mercoledì",
    "                   S. Giovanni Bosco",
    "="];
}
